<?php

/*
 * Copyright (c) 2026 Estonian Information System Authority
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

declare(strict_types=1);

namespace web_eid\web_eid_authtoken_validation_php\testutil;

use phpseclib3\Crypt\Common\PrivateKey;
use phpseclib3\File\X509;

/**
 * A certificate together with its private key, generated by {@see TestPkiBuilder}.
 */
final class TestPkiCredential
{
    private string $certificatePem;
    private PrivateKey $privateKey;

    public function __construct(string $certificatePem, PrivateKey $privateKey)
    {
        $this->certificatePem = $certificatePem;
        $this->privateKey = $privateKey;
    }

    /**
     * Returns a freshly loaded certificate object.
     *
     * A new instance is returned on every call because phpseclib X509 objects accumulate
     * state: validateSignature() verifies against the CA certificates that loadCA() calls
     * have collected on the object, so sharing instances between tests could hide failures.
     * Loading from PEM also guarantees that signatureSubject is captured from the actual
     * certificate bytes, which phpseclib requires for signature verification.
     */
    public function getCertificate(): X509
    {
        $certificate = new X509();
        $certificate->loadX509($this->certificatePem);
        return $certificate;
    }

    public function getCertificatePem(): string
    {
        return $this->certificatePem;
    }

    public function getPrivateKey(): PrivateKey
    {
        return $this->privateKey;
    }

    /** Returns the decimal string representation of the certificate serial number. */
    public function getSerialNumber(): string
    {
        return $this->getCertificate()
            ->getCurrentCert()["tbsCertificate"]["serialNumber"]
            ->toString();
    }

    public function getSubjectDN(): string
    {
        return $this->getCertificate()->getSubjectDN(X509::DN_STRING);
    }
}
