<html>
<head>
    <meta id="csrftoken" name="csrftoken" content="<?php echo $token;?>"/>
    <meta id="csrfheadername" name="csrfheadername" content="X-CSRF-TOKEN"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <base href="/">
</head>
<body>

<?php echo $content; ?>

</body>
</html>
